language: node_js
node_js:
  - 16

cache:
  directories:
    - 'node_modules'

branches:
  only:
    - master

install:
  - npm install
  - npm run generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_ACCESS_TOKEN
  target_branch: master
  local_dir: dist
  repo: sekcje/sekcje.github.io
  on:
    branch: master